version: "2"

run:
  tests: true
  relative-path-mode: wd

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - lll
    - misspell
    - revive
    - staticcheck
    - unused
  settings:
    lll:
      line-length: 120
      tab-width: 1
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$